services:
  otree:
    build: https://github.com/UtrechtUniversity/FSW-OTree-container.git#main
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      # This file is expected to contain the following variables:
      # GITHUB_USER
      # REPOSITORY
      # ACCESS_TOKEN
      # OTREE_ADMIN_PASSWORD
      - /etc/otree.env
    environment:
      - OTREE_PRODUCTION=1
      - OTREE_AUTH_LEVEL=STUDY
      - DATABASE_URL=postgresql://otree:otree@database/otree

  database:
    # Official Postgres image from DockerHub (we use the latest version)
    image: "postgres:13"
    hostname: "database"

    # By default, a Postgres database is running on the 5432 port.
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=otree # The PostgreSQL user (useful to connect to the database)
      - POSTGRES_PASSWORD=otree # The PostgreSQL password (useful to connect to the database)
      - POSTGRES_DB=otree # The PostgreSQL default database (automatically created at first launch)

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]

    volumes:
      # Database volumes for the data as well as any initialization scripts
      - ./db-data/:/var/lib/postgresql/data/