services:
#  2025-05-23 we use the nginx configuration on research cloud, but keep this
#  service definition here to facilitate local testing
#
#  nginx:
#    depends_on:
#      - otree
#    image: nginx:latest
#    container_name: nginx
#    networks:
#      - default
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - 80:80

  otree:
    build: https://github.com/UtrechtUniversity/FSW-OTree-container.git#main
    depends_on:
      database:
        condition: service_healthy
    restart: always
    hostname: otree
    ports:
      - "8000:8000"
    env_file:
      # This file is expected to contain at least the following variables:
      # GITHUB_USER
      # REPOSITORY
      # ACCESS_TOKEN
      # OTREE_ADMIN_PASSWORD
      - /etc/otree.env
    environment:
      - OTREE_PRODUCTION=1
      - OTREE_AUTH_LEVEL=STUDY
      - DATABASE_URL=postgresql://otree:otree@database/otree

#  locust:
#    image: locustio/locust
#    depends_on:
#      - otree
#    ports:
#      - "8089:8089"
#    volumes:
#      - ./:/mnt/locust
#    command: -f /mnt/locust/locustfile.py

  database:
    # Official Postgres image from DockerHub (we use the latest version)
    image: "postgres:17"
    hostname: "database"
    restart: always
    # By default, a Postgres database is running on the 5432 port.
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=otree # The PostgreSQL user (useful to connect to the database)
      - POSTGRES_PASSWORD=otree # The PostgreSQL password (useful to connect to the database)
      - POSTGRES_DB=otree # The PostgreSQL default database (automatically created at first launch)

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]

    volumes:
      # Database volumes for the data as well as any initialization scripts
      - ./db-data/:/var/lib/postgresql/data/